// Importing createSlice from Redux Toolkit to easily create a slice of the Redux state
import { createSlice } from '@reduxjs/toolkit';

// Initial state of the cart slice
const initialState = {
  items: [],
  wishlist: [],
};

// Creating the cart slice with initial state, name, and reducer functions
const cartSlice = createSlice({
  name: 'cart',
  initialState,
  reducers: {
    // Adds an item to the cart. If item already exists, increase its quantity
    addToCart: (state, action) => {
      const item = state.items.find(i => i.id === action.payload.id);
      const qty = action.payload.quantity ? action.payload.quantity : 1;
      if (item) {
        item.quantity += qty;
      } else {
        state.items.push({ ...action.payload, quantity: qty });
      }
    },
    // Adds an item to the wishlist if it's not already present
    addToWishlist: (state, action) => {
      if (!state.wishlist.find(i => i.id === action.payload.id)) {
        state.wishlist.push(action.payload);
      }
    },
    // Removes an item from the wishlist based on its id
    removeFromWishlist: (state, action) => {
      state.wishlist = state.wishlist.filter(i => i.id !== action.payload);
    },
    // Removes an item from the cart based on its id
    removeFromCart: (state, action) => {
      state.items = state.items.filter(i => i.id !== action.payload);
    },
    // Updates the quantity of a specific item in the cart
    updateCartItem: (state, action) => {
      const { id, quantity } = action.payload;
      const item = state.items.find(i => i.id === id);
      if (item && quantity > 0) {
        item.quantity = quantity;
      }
    },
    // Clears all items from the cart
    clearCart: (state) => {
      state.items = [];
    },
  },
});

// Exporting action creators generated by createSlice
export const { addToCart, removeFromCart, updateCartItem, clearCart, addToWishlist, removeFromWishlist } = cartSlice.actions;
// Selector to get all cart items from the state
export const selectCartItems = state => state.cart.items;
// Selector to get the total quantity of items in the cart
export const selectCartCount = state => state.cart.items.reduce((sum, item) => sum + item.quantity, 0);
// Selector to get all wishlist items from the state
export const selectWishlistItems = state => state.cart.wishlist;
// Exporting the reducer to be added to the store
export default cartSlice.reducer; 